# If you need to 'vendor your gems' for deploying your daemons, bundler is a
# great option. Update this Gemfile with any additional dependencies and run
# 'gem bundle' to get them all unpacked in vendor/gems.

# daemon-kit
gem 'daemon-kit'
gem 'amqp'
gem 'json' # Can be replaced with json_pure

# For more information on bundler, please visit http://github.com/wycats/bundler
